"""Rust ↔ Python parity harness (validation-audit Part B2).

Loads ``tests/data/parity_fixtures.json`` — generated by
``cargo run --release --example generate_parity_fixtures`` — and evaluates the
pure-Python mirror of every fixture group on the same inputs, asserting
agreement to the per-group relative tolerance declared by the generator.

Set the ``SPECTROXIDE_PARITY_FIXTURE`` environment variable to test against a
freshly regenerated fixture (the CI parity job does this so that drift on
either side fails CI).
"""

import json
import os
from pathlib import Path

import numpy as np
import pytest

from spectroxide.cosmology import (
    DEFAULT_COSMO,
    PLANCK2018_COSMO,
    baryon_photon_ratio,
    cosmic_time,
    hubble,
    ionization_fraction,
    n_hydrogen,
    omega_gamma,
    rho_gamma,
)
from spectroxide.dark_photon import (
    gamma_con,
    plasma_frequency_ev,
    resonance_redshift,
)
from spectroxide.greens import (
    _photon_survival_probability_numerical,
    _y_compton,
    greens_function,
    greens_function_photon,
    g_bb,
    j_bb,
    j_bb_star,
    j_mu,
    j_y,
    mu_from_photon_injection,
    mu_shape,
    photon_survival_probability,
    planck,
    x_c,
    x_c_br,
    x_c_dc,
    y_shape,
)

_FIXTURE_PATH = Path(
    os.environ.get(
        "SPECTROXIDE_PARITY_FIXTURE",
        Path(__file__).parent / "data" / "parity_fixtures.json",
    )
)


def _scalar(fn):
    """Wrap a vectorized function so it returns a plain float."""

    def wrapper(*args, **kwargs):
        return float(np.asarray(fn(*args, **kwargs)).ravel()[0])

    return wrapper


# Group name -> callable(inputs_row, cosmo_dict_or_None) -> float | tuple | None
_DISPATCH = {
    "visibility_j_bb": lambda i, c: _scalar(j_bb)(i[0]),
    "visibility_j_bb_star": lambda i, c: _scalar(j_bb_star)(i[0]),
    "visibility_j_y": lambda i, c: _scalar(j_y)(i[0]),
    "visibility_j_mu": lambda i, c: _scalar(j_mu)(i[0]),
    "greens_function": lambda i, c: _scalar(greens_function)(i[0], i[1]),
    "x_c_dc": lambda i, c: _scalar(x_c_dc)(i[0]),
    "x_c_br": lambda i, c: _scalar(x_c_br)(i[0]),
    "x_c": lambda i, c: _scalar(x_c)(i[0]),
    "photon_survival_probability": lambda i, c: _scalar(photon_survival_probability)(
        i[0], i[1]
    ),
    "photon_survival_probability_numerical": lambda i, c: float(
        _photon_survival_probability_numerical(i[0], i[1], c)
    ),
    "planck": lambda i, c: _scalar(planck)(i[0]),
    "g_bb": lambda i, c: _scalar(g_bb)(i[0]),
    "mu_shape": lambda i, c: _scalar(mu_shape)(i[0]),
    "y_shape": lambda i, c: _scalar(y_shape)(i[0]),
    "hubble": lambda i, c: float(hubble(i[0], c)),
    "n_hydrogen": lambda i, c: float(n_hydrogen(i[0], c)),
    "baryon_photon_ratio": lambda i, c: float(baryon_photon_ratio(i[0], c)),
    "rho_gamma": lambda i, c: float(rho_gamma(i[0], c)),
    "omega_gamma": lambda i, c: float(omega_gamma(c)),
    "cosmic_time": lambda i, c: float(cosmic_time(i[0], c)),
    "ionization_fraction": lambda i, c: float(ionization_fraction(i[0], c)),
    "compton_y_parameter": lambda i, c: float(_y_compton(i[0], c)),
    "plasma_frequency_ev": lambda i, c: float(plasma_frequency_ev(i[0], c)),
    "resonance_redshift": lambda i, c: resonance_redshift(i[0], c),
    "gamma_con": lambda i, c: gamma_con(1.0e-7, i[0], c),
    "greens_function_photon": lambda i, c: _scalar(greens_function_photon)(
        i[0], i[1], i[2], i[3], cosmo=c
    ),
    "mu_from_photon_injection": lambda i, c: float(
        mu_from_photon_injection(i[0], i[1], i[2])
    ),
}

_COSMO = {"default": DEFAULT_COSMO, "planck2018": PLANCK2018_COSMO, "none": None}


def _load_groups():
    if not _FIXTURE_PATH.exists():
        pytest.fail(
            f"parity fixture not found: {_FIXTURE_PATH}. Regenerate with "
            "`cargo run --release --example generate_parity_fixtures`."
        )
    with open(_FIXTURE_PATH) as f:
        data = json.load(f)
    assert data["schema"] == 1
    return data["groups"]


_GROUPS = _load_groups()


def _group_id(group):
    return f"{group['name']}[{group['cosmo']}]"


@pytest.mark.parametrize("group", _GROUPS, ids=_group_id)
def test_parity(group):
    fn = _DISPATCH.get(group["name"])
    assert fn is not None, f"no Python dispatch for fixture group {group['name']}"
    cosmo = _COSMO[group["cosmo"]]
    rtol = group["rtol"]

    failures = []
    for inp, rust_val in zip(group["inputs"], group["values"]):
        py_val = fn(inp, cosmo)

        # Normalise both sides to tuple-or-None
        if isinstance(py_val, tuple):
            py_tuple = None if py_val[0] is None else tuple(float(v) for v in py_val)
        elif py_val is None or not np.isfinite(py_val):
            py_tuple = None
        else:
            py_tuple = (float(py_val),)
        rust_tuple = None if rust_val is None else tuple(rust_val)

        if (py_tuple is None) != (rust_tuple is None):
            failures.append(f"  inputs={inp}: rust={rust_tuple} python={py_tuple}")
            continue
        if py_tuple is None:
            continue

        for a, b in zip(rust_tuple, py_tuple):
            denom = max(abs(a), abs(b))
            if denom == 0.0:
                continue
            rel = abs(a - b) / denom
            if rel > rtol:
                failures.append(
                    f"  inputs={inp}: rust={a:.12e} python={b:.12e} "
                    f"rel={rel:.3e} > rtol={rtol:.1e}"
                )

    assert not failures, (
        f"{len(failures)} parity failures in group {_group_id(group)} "
        f"(note: {group['note']}):\n" + "\n".join(failures[:20])
    )


def test_all_fixture_groups_have_dispatch():
    """Every group in the fixture must have a Python mirror registered."""
    names = {g["name"] for g in _GROUPS}
    missing = names - set(_DISPATCH)
    assert not missing, f"fixture groups without Python dispatch: {missing}"
